site_name: Reverse Engineering | PC_volt
site_url: https://pc_volt.com/
nav:

    - CheatEngine:
        - CheatEngine: cheatengine/cheatengine.md
    - Ghidra:
        - Setup: ghidra/ghidra_setup.md
        - Open a new Project: ghidra/new_project.md
        - Keybinds: ghidra/keybinds.md
        - Find the Hierarchy: ghidra/hierarchy.md
        - Search for Strings: ghidra/search_for_strings.md
        - Naming conventions: ghidra/naming_conventions.md
    - C++:
        - Static: cpp/static.md
        - Pointers and References: cpp/pointers_references.md
        - Member Initialization List: cpp/initializer_list.md
        - Lambda Functions: cpp/lambdas.md
        - Smart Pointers: cpp/smart_pointers.md
        - vtables: cpp/vtables.md
        - Type Casting: cpp/type_casting.md
    - ASM:
        - Registers: ASM/registers.md
        - Stack: ASM/stack.md
    - Else:
        - Create a Symbolic Link: else/create_symlink.md 

theme: readthedocs